version: '2'

services:
  database:
    image: mysql:5.7
    environment: 
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    networks: 
      - backend
  wordpress:
    image: wordpress:4.9.8
    depends_on: 
      - database
    environment: 
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=password
    networks: 
      - backend
      - frontend
  db:
    image: mariadb
    environment:
      - MYSQL_USER=ghostuser
      - MYSQL_PASSWORD=ghostpassword
      - MYSQL_DATABASE=ghostdb
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    networks:
      - backend
  ghost:
    image: ghost:1-alpine
    depends_on:
      - db
    ports:
      - 8085:2368
    environment:
      - database__client:mysql
      - database__connection__host:db
      - database__connection__user:ghostuser
      - database__connection__password:ghostpassword
      - database__connection__database:ghostdb
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:1.15
    depends_on: 
      - wordpress
    volumes:
      - /etc/ssl/private:/etc/ssl/certs
      - /var/www/html:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      #- ./default4.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      - 443:443
#    command: nginx -t && service nginx start
    networks: 
      - frontend
    links:
      - fpm

  fpm:
    image: php:fpm
    volumes:
      - /var/www/html:/var/www/html
      - ./php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
    networks:
      - frontend
networks:
  backend:
  frontend:
